const homeData = [
    {
        id: 1,
        siteName: 'Summit Structures',
        customerName: 'Nyein Chan',
        staffName: 'Yan Myo',
        location: 'No. 25, Aung Zeya Road, Lanmadaw Township, Yangon, Myanmar',
        operation: 'Foundation Work',
    },
    {
        id: 2,
        siteName: 'Horizon Development',
        customerName: 'Hlaing Win',
        staffName: 'Bo Bo Min',
        location: '123 Mandalay Street, Chan Aye Tharzan Township, Mandalay, Myanmar',
        operation: 'Brick Work',
    },
    {
        id: 3,
        siteName: 'BluePrint Construction',
        customerName: 'Min Zaw',
        staffName: 'Win Shwe',
        location: '45 Bagan Road, Nyaung U Township, Bagan, Mandalay Region, Myanmar',
        operation: 'Roofing',
    },
    {
        id: 4,
        siteName: 'Precision Foundations',
        customerName: 'Aung Ko',
        staffName: 'Htet Aung',
        location: 'No. 8, Kyun Taw Street, Kyauk Taw Township, Rakhine State, Myanmar',
        operation: 'MEP',
    },
    {
        id: 5,
        siteName: 'Fortress Constructors',
        customerName: 'Khin Zaw',
        staffName: 'Nanda Htet',
        location: '67 Shwe Dagon Road, Mingalar Taung Nyunt Township, Yangon, Myanmar',
        operation: 'MEP',
    },
    {
        id: 6,
        siteName: 'Steadfast Builders',
        customerName: 'Kyaw Zin',
        staffName: 'Zin Thant',
        location: '1B, Pyin Oo Lwin Hill, Pyin Oo Lwin District, Mandalay Region, Myanmar',
        operation: 'MEP',
    },
    {
        id: 7,
        siteName: 'Vanguard Creations',
        customerName: 'Zaw Min',
        staffName: 'Ye Kyaw',
        location: '45 Bagan Road, Nyaung U Township, Bagan, Mandalay Region, Myanmar',
        operation: 'MEP',
    },
];

export default homeData;