const staffs = [
  {
    id: 1,
    img: "https://via.placeholder.com/50",
    name: "John Doe",
    department: "IT",
    type: "Administrator",
    email: "john.doe@example.com",
    phone: "+1234567890",
    address: "123 Main St, City, Country",
  },
  {
    id: 2,
    img: "https://via.placeholder.com/50",
    name: "Jane Smith",
    department: "HR",
    type: "Manager",
    email: "jane.smith@example.com",
    phone: "+1234567891",
    address: "456 Oak Ave, City, Country",
  },
  {
    id: 3,
    img: "https://via.placeholder.com/50",
    name: "Robert Brown",
    department: "Finance",
    type: "Administrator",
    email: "robert.brown@example.com",
    phone: "+1234567892",
    address: "789 Pine St, City, Country",
  },
  {
    id: 4,
    img: "https://via.placeholder.com/50",
    name: "Emily White",
    department: "Marketing",
    type: "Coordinator",
    email: "emily.white@example.com",
    phone: "+1234567893",
    address: "101 Maple Rd, City, Country",
  },
  {
    id: 5,
    img: "https://via.placeholder.com/50",
    name: "Michael Green",
    department: "IT",
    type: "Administrator",
    email: "michael.green@example.com",
    phone: "+1234567894",
    address: "234 Cedar Ln, City, Country",
  },
  {
    id: 6,
    img: "https://via.placeholder.com/50",
    name: "Sarah Black",
    department: "Legal",
    type: "Attorney",
    email: "sarah.black@example.com",
    phone: "+1234567895",
    address: "345 Birch Blvd, City, Country",
  },
  {
    id: 7,
    img: "https://via.placeholder.com/50",
    name: "David Wilson",
    department: "Operations",
    type: "Supervisor",
    email: "david.wilson@example.com",
    phone: "+1234567896",
    address: "567 Aspen Dr, City, Country",
  },
  {
    id: 8,
    img: "https://via.placeholder.com/50",
    name: "Emma King",
    department: "Sales",
    type: "Administrator",
    email: "emma.king@example.com",
    phone: "+1234567897",
    address: "678 Elm St, City, Country",
  },
  {
    id: 9,
    img: "https://via.placeholder.com/50",
    name: "James Lee",
    department: "Customer Service",
    type: "Representative",
    email: "james.lee@example.com",
    phone: "+1234567898",
    address: "789 Spruce St, City, Country",
  },
  {
    id: 10,
    img: "https://via.placeholder.com/50",
    name: "Sophia Scott",
    department: "Product",
    type: "Administrator",
    email: "sophia.scott@example.com",
    phone: "+1234567899",
    address: "890 Cherry St, City, Country",
  }
];

export default staffs;
